#!/usr/bin/env bash

# run bellow commands to install mkcert
# mkcert -install

mkcert "$@"

# openssl req \
#     -newkey rsa:2048 \
#     -x509 \
#     -nodes \
#     -keyout "$1.key.pem" \
#     -new \
#     -out "$1.cert.pem" \
#     -subj /"CN=*.$1" \
#     -reqexts SAN \
#     -extensions SAN \
#     -config <(cat /etc/ssl/openssl.cnf \
#         <(printf "[SAN]\nsubjectAltName=DNS:*.$1")) \
#     -sha256 \
#     -days 3650

