#!/usr/bin/env bash

cwd=`pwd`

function findMakefile () {
    if [ ! -f "makefile" ]; then
        cd ..
        findMakefile
    fi
}

if [ "$1" == "docker-start" ]; then
    run docker-down
    findMakefile
    APP="`basename $cwd`" CMD="$2" make up

    cd "$pwd"

    exit 0
fi

if [ "$1" == "docker-down" ]; then
    if [ ! -z "$(docker ps -aq)" ]; then
        docker stop $(docker ps -aq) && docker rm $(docker ps -aq)
    else
        echo "No running containers"
    fi

    exit 0
fi

if [ "$1" == "edit-makefile" ]; then
    findMakefile
    code Makefile
    cd $cwd
    exit 0
fi

if [ "$1" == "show-makefile" ]; then
    findMakefile
    less Makefile
    cd $cwd
    exit 0
fi

findMakefile
cmd="$1"
shift
APP="`basename $cwd`" CMD="$@" make "$cmd"
cd $cwd

# vi:ft=sh
