#!/usr/bin/env bash

subnet_addr="$1"
ip_addr_hex=$(printf '%.2X%.2X%.2X%.2X\n' `echo $subnet_addr | sed -e 's/\./ /g'`)
next_ip_addr_hex=$(printf %.8X `echo $(( 0x$ip_addr_hex + 1 ))`)
gateway_addr=$(printf '%d.%d.%d.%d\n' `echo $next_ip_addr_hex | sed -r 's/(..)/0x\1 /g'`)
net_name="$2"
{
    net_hash=$(docker network create \
      --driver=bridge \
      --subnet=$subnet_addr/16 \
      --ip-range=$subnet_addr/24 \
      --gateway=$gateway_addr \
      "$net_name")
} &>/dev/null && \
echo -e "$net_name\t$gateway_addr\t$net_hash" >> $HOME/.docker-external-networks && \
echo "Created network: $net_name (gateway address: $gateway_addr, network hash: $net_hash)" ||
echo "Error while creating network: $net_name" && exit 1
exit 0
