#!/usr/bin/env bash

if [[ ! -z "$1" ]];then
    site="$1"
else
    site=$(printf "left\nright\ndisable" | dmenu -i -p "Select:")
fi

if [ x"empty" = x"${site}" ]; then
    setscreen
elif [ -n "${site}" ]; then
    if [ "${site}" = "disable"]; then
        xrandr --output HDMI-2 --off
    else
        xrandr --output HDMI-2 --mode 1920x1080 --"${site}"-of eDP-1
    fi
fi

# vi:ft=sh
