#!/bin/sh

# Prompt for confirmation
# $1: Prompt
# $2: Command to run if confirmed

[ "$(printf "No\\nYes" | rofi -dmenu -i -p "$1" -theme-str 'listview { scrollbar: false; }' -theme-str 'window { width: 20%; }' -theme-str 'listview { lines: 2; }' -theme-str 'entry { selected-color: #ff0000; }' )" = "Yes" ] && $2

