#!/usr/bin/env bash

UNAME="jendrusha"
GNAME="wheel"
UUID=1000
UGID=998

docker build -t "my/go:latest" -f - . <<EOT
    FROM golang:latest

    RUN \
        groupadd -g $UGID -o $GNAME && \
        useradd -m -d /workspace -u $UUID -g $UGID -o -s /bin/bash $UNAME

    USER $UNAME

    WORKDIR /workspace/app
EOT
