#!/usr/bin/env node

const util = require('util')
const exec = util.promisify(require('child_process').exec)

async function aware() {
  let capacity = await getCapacity();
  let isCharging = await getIsCharging();

  let title = "'Low battery " + capacity.trim(" ") + "%'"
  let body = "'Connect for charging'"

  if (capacity < 15 && ! isCharging) {
    await exec("notify-send " + title + " " + body)
  }
}

async function getCapacity() {
  const { stdout, stderr } = await exec('cat /sys/class/power_supply/BAT0/capacity')

  if (stderr) {
    console.log(err)

    return
  }

  return stdout
}

async function getIsCharging() {
  const { stdout, stderr } = await exec('cat /sys/class/power_supply/BAT0/status')

  if (stderr) {
    console.log(err)

    return
  }

  return stdout.trim(" ") === "Charging"
}

aware()
