#!/usr/bin/env bash

doTranslate () {
    language=$(echo -e "pl\nen" | dmenu -i -p "Select translate to language")

    if [ -n "$language" ] && [ -n "$text" ]; then
        case "$language" in
          "pl") xdg-open "https://translate.google.com/#en/pl/$text" ;;
          "en") xdg-open "https://translate.google.com/#pl/en/$text" ;;
        esac
        clear
    else
        echo "Ups! Wrong language!"
    fi
}

if [ "$1" == "i" ]; then
    text=$(echo -e "" | dmenu -i -p "Text")
    doTranslate
else
    text="$(xclip -o)"
    # text="$(xclip -o -sel clip)"
    doTranslate
fi

