#!/bin/sh

alias \
    ka="killall" \
	mkd="mkdir -pv" \
	lsall="ls -lahN --color=auto --group-directories-first" \
    dotf="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME" \
    copy="xclip -selection clipboard" \
    x="exit" \
    c="clear" \
    o="wd" \
    rcli="source $HOME/.zshrc" \
    ecli="$EDITOR $HOME/.zshrc" \
    rm='echo "This is not the command you are looking for."; false' \
    ia='comm -23 <(pacman -Qqett | sort) <(pacman -Qqg base -g base-devel | sort | uniq)'

command -v nvim >/dev/null && alias vim="$EDITOR" vimdiff="$EDITOR -d" nvi="$EDITOR"
