#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config normal_border_color  "#0A0E14"
bspc config focused_border_color "#000000"
bspc config window_gap          25

bspc config focused_border_color "#0A0E14"
bspc config normal_border_color  "#0A0E14"

bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 10
bspc config left_padding 0

bspc config split_ratio          0.5

bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a Slack desktop='^5'
bspc rule -a Upwork desktop='^6' state=floating follow=on
bspc rule -a Hubstaff desktop='^6' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
